import { SavedSwapDefinition } from "../../libraries/types/savedata/savedSwapDefinition";

export const SWAP_DEFAULTS: SavedSwapDefinition[] = [
    {
        id: 1,
        kind: "plain",
        source: "...",
        replacement: "…",
        enabled: true,
    },
    {
        id: 2,
        kind: "plain",
        source: "1/2",
        replacement: "½",
        enabled: true,
    },
    {
        id: 3,
        kind: "plain",
        source: "1/3",
        replacement: "⅓",
        enabled: true,
    },
    {
        id: 4,
        kind: "plain",
        source: "1/4",
        replacement: "¼",
        enabled: true,
    },
    {
        id: 5,
        kind: "plain",
        source: "1/5",
        replacement: "⅕",
        enabled: true,
    },
    {
        id: 6,
        kind: "plain",
        source: "1/6",
        replacement: "⅙",
        enabled: true,
    },
    {
        id: 6,
        kind: "plain",
        source: "1/7",
        replacement: "⅐",
        enabled: true,
    },
    {
        id: 6,
        kind: "plain",
        source: "1/9",
        replacement: "⅑",
        enabled: true,
    },
    {
        id: 7,
        kind: "plain",
        source: "1/10",
        replacement: "⅒",
        enabled: true,
    },
    {
        id: 8,
        kind: "plain",
        source: "1/8",
        replacement: "⅛",
        enabled: true,
    },
    {
        id: 9,
        kind: "plain",
        source: "2/3",
        replacement: "⅔",
        enabled: true,
    },
    {
        id: 10,
        kind: "plain",
        source: "2/5",
        replacement: "⅖",
        enabled: true,
    },
    {
        id: 11,
        kind: "plain",
        source: "3/4",
        replacement: "¾",
        enabled: true,
    },
    {
        id: 12,
        kind: "plain",
        source: "3/5",
        replacement: "⅗",
        enabled: true,
    },
    {
        id: 13,
        kind: "plain",
        source: "4/5",
        replacement: "⅘",
        enabled: true,
    },
    {
        id: 14,
        kind: "plain",
        source: "5/6",
        replacement: "⅚",
        enabled: true,
    },
    {
        id: 15,
        kind: "plain",
        source: "3/8",
        replacement: "⅜",
        enabled: true,
    },
    {
        id: 16,
        kind: "plain",
        source: "5/8",
        replacement: "⅝",
        enabled: true,
    },
    {
        id: 17,
        kind: "plain",
        source: "7/8",
        replacement: "⅞",
        enabled: true,
    },
    {
        id: 18,
        kind: "plain",
        source: "<--",
        replacement: "←",
        enabled: true,
    },
    {
        id: 19,
        kind: "plain",
        source: "-->",
        replacement: "→",
        enabled: true,
    },
    {
        id: 20,
        kind: "plain",
        source: "<->",
        replacement: "↔",
        enabled: true,
    },
    {
        id: 21,
        kind: "plain",
        source: "!=",
        replacement: "≠",
        enabled: true,
    },
    {
        id: 22,
        kind: "plain",
        source: "<=",
        replacement: "≤",
        enabled: true,
    },
    {
        id: 23,
        kind: "plain",
        source: ">=",
        replacement: "≥",
        enabled: true,
    },
    {
        id: 24,
        kind: "plain",
        source: "~=",
        replacement: "≅",
        enabled: true,
    },
    {
        id: 25,
        kind: "plain",
        source: "+-",
        replacement: "±",
        enabled: true,
    },
    {
        id: 26,
        kind: "plain",
        source: "-+",
        replacement: "∓",
        enabled: true,
    },
    {
        id: 27,
        kind: "plain",
        source: "<<",
        replacement: "≪",
        enabled: true,
    },
    {
        id: 28,
        kind: "plain",
        source: "≪<",
        replacement: "⋘",
        enabled: true,
    },
    {
        id: 29,
        kind: "plain",
        source: ">>",
        replacement: "≫",
        enabled: true,
    },
    {
        id: 30,
        kind: "plain",
        source: "≫>",
        replacement: "⋙",
        enabled: true,
    },
]
